### ISSUE TITLE
index.js missing

### ISSUE THREAD

**Issue by thegreatpissant** [JoeLudwig/rtc_tabs#1]
package.json has "main" declared as index.js but .gitignore has a setting to ignore *.js.  I think this prevented index.js from being included in the repo and is not able to be found.

This causes webpack to fail during the start and build process.

**Comment by JoeLudwig** [comment]
There is no index.js since the code is written in typescript.  The webpack build didn't fail for me... changed package.json to point to a file that exists anyway.
